-- Propel — consolidated schema from legacy api/migrations
-- Generated by scripts/consolidate-supabase-migrations.mjs — do not edit by hand

CREATE EXTENSION IF NOT EXISTS "pgcrypto";
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ─── from api/migrations/001_schema.sql ───
-- Propel — Standalone PostgreSQL Schema
-- No Supabase dependencies. All auth handled by Propel API JWT.
-- Run via: npm run db:migrate

-- ─── Organizations ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS organizations (
  id          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name        text        NOT NULL,
  slug        text        NOT NULL UNIQUE,
  domain      text,
  logo_url    text,
  plan        text        NOT NULL DEFAULT 'free',
  settings    jsonb       NOT NULL DEFAULT '{}',
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- ─── Users ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS users (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  email           text        NOT NULL UNIQUE,
  password_hash   text        NOT NULL,
  name            text        NOT NULL,
  role            text        NOT NULL DEFAULT 'sales_rep'
                              CHECK (role IN ('owner','admin','manager','sales_rep','viewer')),
  job_title       text,
  avatar_url      text,
  is_active       boolean     NOT NULL DEFAULT true,
  organization_id uuid        REFERENCES organizations(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_users_org ON users(organization_id);
CREATE INDEX IF NOT EXISTS idx_users_email ON users(email);

-- ─── Invitations ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS invitations (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email           text        NOT NULL,
  role            text        NOT NULL DEFAULT 'sales_rep',
  token           text        NOT NULL UNIQUE DEFAULT replace(gen_random_uuid()::text || gen_random_uuid()::text, '-', ''),
  invited_by      uuid        REFERENCES users(id) ON DELETE SET NULL,
  status          text        NOT NULL DEFAULT 'pending',
  expires_at      timestamptz NOT NULL DEFAULT now() + interval '7 days',
  created_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE(email, organization_id)
);

-- ─── Companies ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS companies (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name            text        NOT NULL,
  domain          text,
  industry        text,
  size            text,
  country         text,
  city            text,
  website         text,
  phone           text,
  revenue         numeric,
  status          text        NOT NULL DEFAULT 'prospect',
  tags            text[]      NOT NULL DEFAULT '{}',
  notes           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_companies_org ON companies(organization_id);

-- ─── Contacts ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS contacts (
  id               uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id  uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  first_name       text        NOT NULL,
  last_name        text        NOT NULL DEFAULT '',
  email            text,
  phone            text,
  job_title        text,
  company_id       uuid        REFERENCES companies(id) ON DELETE SET NULL,
  status           text        NOT NULL DEFAULT 'prospect',
  type             text        NOT NULL DEFAULT 'lead' CHECK (type IN ('lead','contact')),
  source           text        NOT NULL DEFAULT 'other',
  lead_score       integer     NOT NULL DEFAULT 50,
  tags             text[]      NOT NULL DEFAULT '{}',
  notes            text,
  assigned_to      uuid        REFERENCES users(id) ON DELETE SET NULL,
  last_contacted_at timestamptz,
  linked_deals     text[]      NOT NULL DEFAULT '{}',
  created_at       timestamptz NOT NULL DEFAULT now(),
  updated_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_contacts_org ON contacts(organization_id);
CREATE INDEX IF NOT EXISTS idx_contacts_company ON contacts(company_id);
CREATE INDEX IF NOT EXISTS idx_contacts_email ON contacts(organization_id, email);

-- ─── Deals ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS deals (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id     uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  title               text        NOT NULL,
  value               numeric     NOT NULL DEFAULT 0,
  currency            text        NOT NULL DEFAULT 'USD',
  stage               text        NOT NULL DEFAULT 'lead',
  status              text        NOT NULL DEFAULT 'open' CHECK (status IN ('open','won','lost')),
  contact_id          uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  company_id          uuid        REFERENCES companies(id) ON DELETE SET NULL,
  owner_id            uuid        REFERENCES users(id) ON DELETE SET NULL,
  assigned_to         uuid        REFERENCES users(id) ON DELETE SET NULL,
  expected_close_date date,
  closed_at           timestamptz,
  quote_items         jsonb       NOT NULL DEFAULT '[]',
  tags                text[]      NOT NULL DEFAULT '{}',
  notes               text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deals_org ON deals(organization_id);
CREATE INDEX IF NOT EXISTS idx_deals_stage ON deals(organization_id, stage);

-- ─── Activities ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS activities (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  type            text        NOT NULL CHECK (type IN ('call','email','meeting','task','note','demo','follow_up')),
  subject         text        NOT NULL,
  description     text        NOT NULL DEFAULT '',
  outcome         text,
  due_date        timestamptz,
  completed_at    timestamptz,
  status          text        NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','completed','cancelled')),
  contact_id      uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  company_id      uuid        REFERENCES companies(id) ON DELETE SET NULL,
  deal_id         uuid        REFERENCES deals(id) ON DELETE SET NULL,
  created_by      text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_activities_org ON activities(organization_id);
CREATE INDEX IF NOT EXISTS idx_activities_deal ON activities(deal_id);
CREATE INDEX IF NOT EXISTS idx_activities_contact ON activities(contact_id);

-- ─── Notifications ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  type            text        NOT NULL,
  title           text        NOT NULL,
  message         text        NOT NULL DEFAULT '',
  entity_type     text,
  entity_id       text,
  user_id         text        NOT NULL DEFAULT 'system',
  triggered_by    text,
  is_read         boolean     NOT NULL DEFAULT false,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_notifications_org_user ON notifications(organization_id, user_id);

-- ─── Audit Log ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS audit_log (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  action          text        NOT NULL,
  entity_type     text        NOT NULL,
  entity_id       text        NOT NULL,
  entity_name     text        NOT NULL DEFAULT '',
  details         text        NOT NULL DEFAULT '',
  user_id         text        NOT NULL DEFAULT 'system',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_audit_org ON audit_log(organization_id, created_at DESC);

-- ─── Products ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS products (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name            text        NOT NULL,
  description     text,
  sku             text,
  price           numeric     NOT NULL DEFAULT 0,
  currency        text        NOT NULL DEFAULT 'EUR',
  category        text,
  is_active       boolean     NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Email Templates ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_templates (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name            text        NOT NULL,
  subject         text        NOT NULL,
  body            text        NOT NULL DEFAULT '',
  category        text        NOT NULL DEFAULT 'general'
                              CHECK (category IN ('outreach','follow_up','proposal','onboarding','general')),
  variables       text[]      NOT NULL DEFAULT '{}',
  usage_count     integer     NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Quick Replies ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS quick_replies (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id         uuid        REFERENCES users(id) ON DELETE SET NULL,
  title           text        NOT NULL,
  body            text        NOT NULL DEFAULT '',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Sales Goals ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sales_goals (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id         uuid        REFERENCES users(id) ON DELETE SET NULL,
  type            text        NOT NULL,
  target          numeric     NOT NULL DEFAULT 0,
  current         numeric     NOT NULL DEFAULT 0,
  period          text        NOT NULL DEFAULT 'monthly',
  start_date      date        NOT NULL,
  end_date        date        NOT NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Automation Rules ────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS automation_rules (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name            text        NOT NULL,
  description     text        NOT NULL DEFAULT '',
  is_active       boolean     NOT NULL DEFAULT true,
  trigger         jsonb       NOT NULL DEFAULT '{}',
  actions         jsonb       NOT NULL DEFAULT '[]',
  execution_count integer     NOT NULL DEFAULT 0,
  last_executed_at timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Automation Executions ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS automation_executions (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  rule_id         uuid        REFERENCES automation_rules(id) ON DELETE SET NULL,
  trigger_type    text        NOT NULL,
  status          text        NOT NULL DEFAULT 'success' CHECK (status IN ('success','error')),
  context         jsonb       NOT NULL DEFAULT '{}',
  result          jsonb       NOT NULL DEFAULT '{}',
  error_message   text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_auto_exec_org ON automation_executions(organization_id, created_at DESC);

-- ─── Email Sequences ─────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_sequences (
  id                          uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id             uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name                        text        NOT NULL,
  description                 text        NOT NULL DEFAULT '',
  steps                       jsonb       NOT NULL DEFAULT '[]',
  flow_definition             jsonb,
  created_by                  uuid        REFERENCES users(id) ON DELETE SET NULL,
  is_active                   boolean     NOT NULL DEFAULT true,
  enrolled_count              integer     NOT NULL DEFAULT 0,
  stop_on_contact_reply       boolean     NOT NULL DEFAULT true,
  enrollment_start_delay_days integer     NOT NULL DEFAULT 0,
  created_at                  timestamptz NOT NULL DEFAULT now()
);

-- ─── Sequence Enrollments ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS sequence_enrollments (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id     uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  sequence_id         uuid        NOT NULL REFERENCES email_sequences(id) ON DELETE CASCADE,
  contact_id          uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  contact_name        text        NOT NULL,
  current_step        integer     NOT NULL DEFAULT 0,
  current_node_id     text,
  ab_variant          text        CHECK (ab_variant IN ('a','b')),
  status              text        NOT NULL DEFAULT 'active'
                                  CHECK (status IN ('active','paused','completed','unenrolled','replied')),
  enrolled_at         timestamptz NOT NULL DEFAULT now(),
  next_step_at        timestamptz,
  completed_at        timestamptz,
  last_sent_thread_id text,
  last_sent_message_id text
);

CREATE INDEX IF NOT EXISTS idx_seq_enr_org ON sequence_enrollments(organization_id);
CREATE INDEX IF NOT EXISTS idx_seq_enr_contact ON sequence_enrollments(contact_id);

-- ─── Custom Field Definitions ────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS custom_field_definitions (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  entity_type     text        NOT NULL,
  label           text        NOT NULL,
  field_type      text        NOT NULL DEFAULT 'text',
  placeholder     text,
  options         jsonb,
  required        boolean     NOT NULL DEFAULT false,
  "order"         integer     NOT NULL DEFAULT 0,
  is_active       boolean     NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── Custom Field Values ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS custom_field_values (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  entity_id       text        NOT NULL,
  field_id        uuid        NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
  value           jsonb,
  UNIQUE(entity_id, field_id)
);

-- ─── Custom Field i18n ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS custom_field_definition_i18n (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  field_id        uuid        NOT NULL REFERENCES custom_field_definitions(id) ON DELETE CASCADE,
  language_code   text        NOT NULL,
  label           text        NOT NULL,
  placeholder     text,
  options         jsonb,
  UNIQUE(field_id, language_code)
);

-- ─── Leads ───────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS leads (
  id                   uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id      uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  first_name           text        NOT NULL,
  last_name            text        NOT NULL,
  email                text        NOT NULL,
  phone                text,
  company_name         text,
  job_title            text,
  source               text        NOT NULL DEFAULT 'website',
  status               text        NOT NULL DEFAULT 'open'
                                   CHECK (status IN ('open','contacted','qualified','disqualified','converted')),
  lifecycle_stage      text        NOT NULL DEFAULT 'lead'
                                   CHECK (lifecycle_stage IN ('lead','mql','sql','opportunity','customer','evangelist')),
  score                integer     NOT NULL DEFAULT 0,
  assigned_to          uuid        REFERENCES users(id) ON DELETE SET NULL,
  owner_user_id        uuid        REFERENCES users(id) ON DELETE SET NULL,
  tags                 jsonb       NOT NULL DEFAULT '[]',
  notes                text,
  last_engaged_at      timestamptz,
  converted_contact_id uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  converted_company_id uuid        REFERENCES companies(id) ON DELETE SET NULL,
  converted_deal_id    uuid        REFERENCES deals(id) ON DELETE SET NULL,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX IF NOT EXISTS leads_unique_email_per_org ON leads(organization_id, lower(email));
CREATE INDEX IF NOT EXISTS idx_leads_org ON leads(organization_id, score DESC);

-- ─── Lead Events ─────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lead_events (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  lead_id         uuid        NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  event_type      text        NOT NULL,
  metadata        jsonb       NOT NULL DEFAULT '{}',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_events_lead ON lead_events(lead_id, created_at DESC);

-- ─── Lead Score Snapshots ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lead_score_snapshots (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  lead_id         uuid        NOT NULL REFERENCES leads(id) ON DELETE CASCADE,
  score           integer     NOT NULL,
  reason          text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_snapshots_lead ON lead_score_snapshots(lead_id, created_at ASC);

-- ─── Lead Scoring Rules ──────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lead_scoring_rules (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  key             text        NOT NULL,
  points          integer     NOT NULL DEFAULT 0,
  is_enabled      boolean     NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE(organization_id, key)
);

-- ─── from api/migrations/002_indexes_and_perf.sql ───
-- ─────────────────────────────────────────────────────────────────────────────
-- Migration 002 — Indexes, performance fixes, and Row Level Security
-- Apply with: psql $DATABASE_URL -f migrations/002_indexes_and_perf.sql
--
-- (index built inline for Supabase migrations)
-- acquiring an AccessShareLock that would block reads or writes.
-- (index built inline for Supabase migrations)
-- outside of BEGIN/COMMIT or use psql directly.
-- ─────────────────────────────────────────────────────────────────────────────

-- ─── 1. pg_trgm extension ────────────────────────────────────────────────────
-- Required for GIN trigram indexes that make ILIKE fast.
CREATE EXTENSION IF NOT EXISTS pg_trgm;


-- ─── 2. GIN trigram indexes for ILIKE search columns ─────────────────────────

-- contacts: first_name, last_name, email, phone
CREATE INDEX IF NOT EXISTS idx_trgm_contacts_first_name
  ON contacts USING GIN (first_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_trgm_contacts_last_name
  ON contacts USING GIN (last_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_trgm_contacts_email
  ON contacts USING GIN (email gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_trgm_contacts_phone
  ON contacts USING GIN (phone gin_trgm_ops);

-- companies: name
CREATE INDEX IF NOT EXISTS idx_trgm_companies_name
  ON companies USING GIN (name gin_trgm_ops);

-- deals: title
CREATE INDEX IF NOT EXISTS idx_trgm_deals_title
  ON deals USING GIN (title gin_trgm_ops);

-- leads: first_name, last_name, email (leads list is a hot search path too)
CREATE INDEX IF NOT EXISTS idx_trgm_leads_first_name
  ON leads USING GIN (first_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_trgm_leads_last_name
  ON leads USING GIN (last_name gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_trgm_leads_email
  ON leads USING GIN (email gin_trgm_ops);


-- ─── 3. B-tree covering indexes on hot tenant-scoped foreign keys ─────────────
-- Pattern: WHERE organization_id = $1 AND <fk> = $2
-- 001_schema.sql already covers the most basic (org, email) and (org) cases;
-- the entries below fill in everything that was missed.

-- contacts.assigned_to scoped to org
CREATE INDEX IF NOT EXISTS idx_contacts_org_assigned
  ON contacts(organization_id, assigned_to);

-- contacts.company_id scoped to org (001 has idx_contacts_company without org)
CREATE INDEX IF NOT EXISTS idx_contacts_org_company
  ON contacts(organization_id, company_id);

-- deals.contact_id scoped to org
CREATE INDEX IF NOT EXISTS idx_deals_org_contact
  ON deals(organization_id, contact_id);

-- deals.company_id scoped to org
CREATE INDEX IF NOT EXISTS idx_deals_org_company
  ON deals(organization_id, company_id);

-- deals.owner_id scoped to org
CREATE INDEX IF NOT EXISTS idx_deals_org_owner
  ON deals(organization_id, owner_id);

-- deals.assigned_to scoped to org
CREATE INDEX IF NOT EXISTS idx_deals_org_assigned
  ON deals(organization_id, assigned_to);

-- activities.company_id scoped to org
CREATE INDEX IF NOT EXISTS idx_activities_org_company
  ON activities(organization_id, company_id);

-- activities.contact_id scoped to org (001 has idx_activities_contact without org)
CREATE INDEX IF NOT EXISTS idx_activities_org_contact
  ON activities(organization_id, contact_id);

-- activities.deal_id scoped to org (001 has idx_activities_deal without org)
CREATE INDEX IF NOT EXISTS idx_activities_org_deal
  ON activities(organization_id, deal_id);

-- sequence_enrollments.sequence_id scoped to org
CREATE INDEX IF NOT EXISTS idx_seq_enr_org_sequence
  ON sequence_enrollments(organization_id, sequence_id);

-- sequence_enrollments.contact_id scoped to org (001 has it without org)
CREATE INDEX IF NOT EXISTS idx_seq_enr_org_contact
  ON sequence_enrollments(organization_id, contact_id);

-- leads.assigned_to scoped to org
CREATE INDEX IF NOT EXISTS idx_leads_org_assigned
  ON leads(organization_id, assigned_to);

-- leads.owner_user_id scoped to org
CREATE INDEX IF NOT EXISTS idx_leads_org_owner
  ON leads(organization_id, owner_user_id);

-- lead_events.organization_id (scan by org before filtering by lead)
CREATE INDEX IF NOT EXISTS idx_lead_events_org
  ON lead_events(organization_id, lead_id, created_at DESC);

-- quick_replies.user_id scoped to org
CREATE INDEX IF NOT EXISTS idx_quick_replies_org_user
  ON quick_replies(organization_id, user_id);

-- sales_goals.user_id scoped to org
CREATE INDEX IF NOT EXISTS idx_sales_goals_org_user
  ON sales_goals(organization_id, user_id);

-- automation_executions.rule_id scoped to org
CREATE INDEX IF NOT EXISTS idx_auto_exec_org_rule
  ON automation_executions(organization_id, rule_id);

-- custom_field_values.field_id scoped to org
CREATE INDEX IF NOT EXISTS idx_cfv_org_field
  ON custom_field_values(organization_id, field_id);

-- notifications: unread lookup (hot path for notification badge)
CREATE INDEX IF NOT EXISTS idx_notifications_unread
  ON notifications(organization_id, user_id, is_read)
  WHERE is_read = false;


-- ─── 4. Composite indexes for common list query patterns ─────────────────────

-- (organization_id, created_at DESC) — default sort on all list endpoints
CREATE INDEX IF NOT EXISTS idx_contacts_org_created
  ON contacts(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_deals_org_created
  ON deals(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_companies_org_created
  ON companies(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_activities_org_created
  ON activities(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_leads_org_created
  ON leads(organization_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_sequences_org_created
  ON email_sequences(organization_id, created_at DESC);

-- (organization_id, status) — filtered list views
CREATE INDEX IF NOT EXISTS idx_deals_org_status
  ON deals(organization_id, status);

CREATE INDEX IF NOT EXISTS idx_contacts_org_status
  ON contacts(organization_id, status);

CREATE INDEX IF NOT EXISTS idx_leads_org_status
  ON leads(organization_id, status);

-- (organization_id, assigned_to) — "my items" filter used on every list view
CREATE INDEX IF NOT EXISTS idx_deals_org_assigned_to
  ON deals(organization_id, assigned_to);

CREATE INDEX IF NOT EXISTS idx_contacts_org_assigned_to
  ON contacts(organization_id, assigned_to);

CREATE INDEX IF NOT EXISTS idx_leads_org_assigned_to
  ON leads(organization_id, assigned_to);


-- ─── 5. Partial index for active email sequences ──────────────────────────────
-- email_sequences uses is_active boolean (not a status text column).
-- This index covers the common "fetch active sequences" query and is kept small
-- because inactive sequences are excluded from the index entirely.
CREATE INDEX IF NOT EXISTS idx_sequences_active
  ON email_sequences(organization_id, created_at DESC)
  WHERE is_active = true;

-- Active sequence enrollments — polled by the sequence runner on every tick
CREATE INDEX IF NOT EXISTS idx_seq_enr_active_next_step
  ON sequence_enrollments(organization_id, next_step_at ASC)
  WHERE status = 'active';

-- ─── from api/migrations/003_gmail_webhooks_tracking.sql ───
-- Migration 003: Gmail tokens, thread links, webhook subscriptions, email tracking

-- ─── Gmail tokens ────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS gmail_tokens (
  id                   uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id      uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  email_address        text        NOT NULL,
  refresh_token        text,
  refresh_token_cipher text,
  access_token         text,
  token_expiry         timestamptz,
  scopes               text,
  google_sub           text,
  name                 text,
  avatar_url           text,
  is_active            boolean     NOT NULL DEFAULT true,
  created_at           timestamptz NOT NULL DEFAULT now(),
  updated_at           timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, organization_id)
);

CREATE INDEX IF NOT EXISTS idx_gmail_tokens_org ON gmail_tokens(organization_id);

-- ─── Gmail thread links ───────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS gmail_thread_links (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id       text        NOT NULL,
  user_id         uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  contact_id      uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  company_id      uuid        REFERENCES companies(id) ON DELETE SET NULL,
  deal_id         uuid        REFERENCES deals(id) ON DELETE SET NULL,
  source          text        NOT NULL DEFAULT 'manual' CHECK (source IN ('auto', 'manual')),
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (thread_id, user_id, organization_id)
);

CREATE INDEX IF NOT EXISTS idx_gmail_thread_links_org_user ON gmail_thread_links(organization_id, user_id);
CREATE INDEX IF NOT EXISTS idx_gmail_thread_links_thread ON gmail_thread_links(thread_id);

-- ─── Webhook subscriptions ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS webhook_subscriptions (
  id                  uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id     uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  created_by          uuid        REFERENCES users(id) ON DELETE SET NULL,
  name                text        NOT NULL,
  target_url          text        NOT NULL,
  enabled             boolean     NOT NULL DEFAULT true,
  event_filters       text[]      NOT NULL DEFAULT ARRAY['*']::text[],
  custom_headers      jsonb       NOT NULL DEFAULT '{}',
  schema_version      smallint    NOT NULL DEFAULT 1,
  last_delivery_at    timestamptz,
  last_http_status    integer,
  last_delivery_error text,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT webhook_subscriptions_https CHECK (target_url ~ '^https://')
);

CREATE INDEX IF NOT EXISTS idx_webhook_subscriptions_org
  ON webhook_subscriptions(organization_id) WHERE enabled = true;

CREATE TABLE IF NOT EXISTS webhook_subscription_secrets (
  subscription_id uuid PRIMARY KEY REFERENCES webhook_subscriptions(id) ON DELETE CASCADE,
  signing_secret  text NOT NULL
);

-- ─── Email tracking ───────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS email_tracking_messages (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  email_id        text        NOT NULL,
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id         uuid        REFERENCES users(id) ON DELETE SET NULL,
  contact_id      uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  company_id      uuid        REFERENCES companies(id) ON DELETE SET NULL,
  deal_id         uuid        REFERENCES deals(id) ON DELETE SET NULL,
  open_token      text        NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_tracking_messages_org
  ON email_tracking_messages(organization_id, email_id);

CREATE TABLE IF NOT EXISTS email_tracking_links (
  id                   uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
  tracking_message_id  uuid  NOT NULL REFERENCES email_tracking_messages(id) ON DELETE CASCADE,
  email_id             text  NOT NULL,
  organization_id      uuid  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  contact_id           uuid  REFERENCES contacts(id) ON DELETE SET NULL,
  original_url         text  NOT NULL,
  click_token          text  NOT NULL UNIQUE DEFAULT gen_random_uuid()::text,
  created_at           timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_tracking_links_org
  ON email_tracking_links(organization_id, email_id);

CREATE TABLE IF NOT EXISTS email_tracking_events (
  id                  uuid  PRIMARY KEY DEFAULT gen_random_uuid(),
  tracking_message_id uuid  NOT NULL REFERENCES email_tracking_messages(id) ON DELETE CASCADE,
  link_id             uuid  REFERENCES email_tracking_links(id) ON DELETE SET NULL,
  email_id            text  NOT NULL,
  organization_id     uuid  NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  contact_id          uuid  REFERENCES contacts(id) ON DELETE SET NULL,
  event_type          text  NOT NULL CHECK (event_type IN ('open', 'click')),
  user_agent          text,
  ip_hash             text,
  created_at          timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_email_tracking_events_org
  ON email_tracking_events(organization_id, email_id, event_type, created_at DESC);

-- ─── from api/migrations/004_api_keys_lead_tokens.sql ───
-- ─── API Keys ────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS api_keys (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name            text        NOT NULL,
  key_prefix      text        NOT NULL,
  key_hash        text        NOT NULL UNIQUE,
  scopes          jsonb       NOT NULL DEFAULT '[]',
  revoked_at      timestamptz,
  last_used_at    timestamptz,
  expires_at      timestamptz,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_api_keys_org ON api_keys(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_api_keys_hash ON api_keys(key_hash) WHERE revoked_at IS NULL;

-- ─── Lead Capture Tokens ─────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS lead_capture_tokens (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  label           text        NOT NULL DEFAULT '',
  token_prefix    text        NOT NULL,
  token_hash      text        NOT NULL UNIQUE,
  enabled         boolean     NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_lead_tokens_org ON lead_capture_tokens(organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_lead_tokens_hash ON lead_capture_tokens(token_hash) WHERE enabled = true;

-- ─── from api/migrations/005_user_phone_smtp.sql ───
-- ─── User profile: phone field ───────────────────────────────────────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS phone text;

-- ─── Per-org SMTP configuration ───────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS org_smtp_settings (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL UNIQUE REFERENCES organizations(id) ON DELETE CASCADE,
  host            text        NOT NULL,
  port            integer     NOT NULL DEFAULT 587,
  username        text        NOT NULL,
  password_enc    text        NOT NULL,
  from_address    text        NOT NULL,
  from_name       text,
  reply_to        text,
  secure          text        NOT NULL DEFAULT 'starttls' CHECK (secure IN ('starttls','ssl','none')),
  is_active       boolean     NOT NULL DEFAULT true,
  last_test_at    timestamptz,
  last_test_ok    boolean,
  last_test_error text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- ─── from api/migrations/006_ux_metric_events.sql ───
-- UX telemetry events (fire-and-forget, non-critical)
CREATE TABLE IF NOT EXISTS ux_metric_events (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid REFERENCES organizations(id) ON DELETE CASCADE,
  user_id         uuid REFERENCES users(id) ON DELETE SET NULL,
  action          text NOT NULL,
  occurred_at     timestamptz NOT NULL DEFAULT now(),
  meta            jsonb,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ux_metric_events_org ON ux_metric_events (organization_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_ux_metric_events_action ON ux_metric_events (action, occurred_at DESC);

-- ─── from api/migrations/007_gmail_thread_workspace.sql ───
-- Per-thread workspace metadata (owner assignment + internal notes)
CREATE TABLE IF NOT EXISTS gmail_thread_workspace (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  thread_id       text NOT NULL,
  user_id         uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  owner_user_id   uuid REFERENCES users(id) ON DELETE SET NULL,
  internal_note   text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  UNIQUE (thread_id, user_id, organization_id)
);

CREATE INDEX IF NOT EXISTS idx_gmail_thread_workspace_org_user
  ON gmail_thread_workspace (organization_id, user_id);

-- ─── from api/migrations/008_pipelines.sql ───
-- Migration 008: Multi-pipeline support
-- Each org can have multiple named pipelines with their own stages.
-- deals.pipeline_id links each deal to a pipeline.

-- ─── Pipelines ───────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS pipelines (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name            text        NOT NULL,
  description     text,
  is_default      boolean     NOT NULL DEFAULT false,
  is_archived     boolean     NOT NULL DEFAULT false,
  -- Ordered array of stage objects: [{id,name,color,order,probability}]
  stages          jsonb       NOT NULL DEFAULT '[]',
  view_access     text        NOT NULL DEFAULT 'all'
                              CHECK (view_access IN ('all', 'members_only')),
  created_by      uuid        REFERENCES users(id) ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

-- Only one default pipeline per org (enforced at app layer + this partial index)
CREATE UNIQUE INDEX IF NOT EXISTS idx_pipelines_org_default
  ON pipelines (organization_id)
  WHERE is_default = true AND is_archived = false;

CREATE INDEX IF NOT EXISTS idx_pipelines_org ON pipelines(organization_id);

-- ─── Pipeline Members ─────────────────────────────────────────────────────────
-- Controls who can access members_only pipelines.
-- admin/owner always have implicit access regardless of membership.
CREATE TABLE IF NOT EXISTS pipeline_members (
  pipeline_id uuid NOT NULL REFERENCES pipelines(id) ON DELETE CASCADE,
  user_id     uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role        text NOT NULL DEFAULT 'member'
              CHECK (role IN ('owner', 'member')),
  added_at    timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (pipeline_id, user_id)
);

CREATE INDEX IF NOT EXISTS idx_pipeline_members_user ON pipeline_members(user_id);

-- ─── Deals: add pipeline_id ──────────────────────────────────────────────────
ALTER TABLE deals
  ADD COLUMN IF NOT EXISTS pipeline_id uuid REFERENCES pipelines(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_deals_pipeline ON deals(pipeline_id);

-- ─── from api/migrations/009_calendar.sql ───
-- Migration 009: Google Calendar sync — events + push-notification channels

-- ─── Calendar events (synced from Google Calendar) ───────────────────────────
CREATE TABLE IF NOT EXISTS calendar_events (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id   uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id           uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  google_event_id   text        NOT NULL,
  google_calendar_id text       NOT NULL DEFAULT 'primary',
  title             text        NOT NULL DEFAULT '',
  description       text,
  location          text,
  start_at          timestamptz NOT NULL,
  end_at            timestamptz NOT NULL,
  all_day           boolean     NOT NULL DEFAULT false,
  status            text        NOT NULL DEFAULT 'confirmed'
                                CHECK (status IN ('confirmed','tentative','cancelled')),
  html_link         text,
  meet_link         text,
  organizer_email   text,
  attendees         jsonb       NOT NULL DEFAULT '[]',
  recurrence        text[],
  contact_id        uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  company_id        uuid        REFERENCES companies(id) ON DELETE SET NULL,
  deal_id           uuid        REFERENCES deals(id) ON DELETE SET NULL,
  synced_at         timestamptz NOT NULL DEFAULT now(),
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, organization_id, google_event_id)
);

CREATE INDEX IF NOT EXISTS idx_calendar_events_org_user_start
  ON calendar_events(organization_id, user_id, start_at);
CREATE INDEX IF NOT EXISTS idx_calendar_events_google_id
  ON calendar_events(google_event_id);
CREATE INDEX IF NOT EXISTS idx_calendar_events_contact
  ON calendar_events(contact_id) WHERE contact_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_calendar_events_deal
  ON calendar_events(deal_id) WHERE deal_id IS NOT NULL;

-- ─── Google Calendar watch channels (push notification subscriptions) ─────────
CREATE TABLE IF NOT EXISTS calendar_watch_channels (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  organization_id   uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  channel_id        text        NOT NULL UNIQUE,
  resource_id       text,
  calendar_id       text        NOT NULL DEFAULT 'primary',
  expiration        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (user_id, organization_id, calendar_id)
);

CREATE INDEX IF NOT EXISTS idx_calendar_watch_org
  ON calendar_watch_channels(organization_id);

-- ─── from api/migrations/010_webhooks.sql ───
-- Inbound webhook registrations (org registers a URL to receive signed pushes)
CREATE TABLE IF NOT EXISTS webhooks (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  url             text NOT NULL,
  events          text[] NOT NULL DEFAULT '{"*"}',
  secret          text,
  active          boolean NOT NULL DEFAULT true,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_webhooks_org ON webhooks(organization_id) WHERE active = true;

-- Received inbound webhook payloads (queued for async processing)
CREATE TABLE IF NOT EXISTS webhook_events (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  payload         jsonb NOT NULL DEFAULT '{}',
  processed       boolean NOT NULL DEFAULT false,
  received_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_webhook_events_org_unprocessed
  ON webhook_events(organization_id, received_at)
  WHERE processed = false;

-- ─── from api/migrations/011_activity_linkedin_type.sql ───
-- Add 'linkedin' as a valid activity type (frontend uses it)
ALTER TABLE activities DROP CONSTRAINT IF EXISTS activities_type_check;
ALTER TABLE activities ADD CONSTRAINT activities_type_check
  CHECK (type = ANY (ARRAY['call','email','meeting','task','note','demo','follow_up','linkedin']));

-- ─── from api/migrations/012_contacts_linkedin_url.sql ───
-- Add LinkedIn profile URL to contacts
ALTER TABLE contacts ADD COLUMN IF NOT EXISTS linkedin_url text;

-- ─── from api/migrations/013_org_branding_billing.sql ───
-- Org branding, billing details, localization, and plan metadata
ALTER TABLE organizations
  ADD COLUMN IF NOT EXISTS primary_color    varchar(7)   DEFAULT '#4f46e5',
  ADD COLUMN IF NOT EXISTS favicon_url      text,
  ADD COLUMN IF NOT EXISTS custom_domain    text,
  ADD COLUMN IF NOT EXISTS billing_email    text,
  ADD COLUMN IF NOT EXISTS billing_name     text,
  ADD COLUMN IF NOT EXISTS billing_address  text,
  ADD COLUMN IF NOT EXISTS billing_city     text,
  ADD COLUMN IF NOT EXISTS billing_country  varchar(2),
  ADD COLUMN IF NOT EXISTS billing_vat      text,
  ADD COLUMN IF NOT EXISTS currency         varchar(3)   DEFAULT 'EUR',
  ADD COLUMN IF NOT EXISTS timezone         text         DEFAULT 'Europe/Madrid',
  ADD COLUMN IF NOT EXISTS date_format      text         DEFAULT 'DD/MM/YYYY',
  ADD COLUMN IF NOT EXISTS quote_footer     text,
  ADD COLUMN IF NOT EXISTS privacy_url      text,
  ADD COLUMN IF NOT EXISTS terms_url        text;

-- Super admin flag on users
ALTER TABLE users
  ADD COLUMN IF NOT EXISTS is_super_admin boolean NOT NULL DEFAULT false;

-- ─── from api/migrations/014_plans_subscriptions.sql ───
-- Plans and subscriptions for multi-tenant billing management

CREATE TABLE IF NOT EXISTS plans (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  name            text        NOT NULL,
  slug            text        NOT NULL UNIQUE,
  description     text,
  price_monthly   numeric(10,2) NOT NULL DEFAULT 0,
  price_yearly    numeric(10,2) NOT NULL DEFAULT 0,
  currency        varchar(3)  NOT NULL DEFAULT 'EUR',
  max_users       integer     NOT NULL DEFAULT 5,
  max_contacts    integer     NOT NULL DEFAULT 1000,
  max_deals       integer     NOT NULL DEFAULT 500,
  max_pipelines   integer     NOT NULL DEFAULT 1,
  features        jsonb       NOT NULL DEFAULT '{}',
  is_active       boolean     NOT NULL DEFAULT true,
  sort_order      integer     NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS subscriptions (
  id                      uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id         uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  plan_id                 uuid        NOT NULL REFERENCES plans(id),
  status                  text        NOT NULL DEFAULT 'active'
                          CHECK (status IN ('trialing','active','past_due','canceled','expired')),
  trial_ends_at           timestamptz,
  current_period_start    timestamptz NOT NULL DEFAULT now(),
  current_period_end      timestamptz,
  stripe_subscription_id  text,
  stripe_customer_id      text,
  notes                   text,
  created_at              timestamptz NOT NULL DEFAULT now(),
  updated_at              timestamptz NOT NULL DEFAULT now(),
  UNIQUE(organization_id)
);

CREATE INDEX IF NOT EXISTS idx_subscriptions_org ON subscriptions(organization_id);
CREATE INDEX IF NOT EXISTS idx_subscriptions_plan ON subscriptions(plan_id);
CREATE INDEX IF NOT EXISTS idx_plans_slug ON plans(slug);

-- Seed default plans
INSERT INTO plans (name, slug, description, price_monthly, price_yearly, max_users, max_contacts, max_deals, max_pipelines, features, sort_order)
VALUES
  ('Free',       'free',       'For individuals and small teams getting started',        0,    0,    3,    500,    200,  1, '{"gmail":false,"calendar":false,"api":false,"webhooks":false}', 0),
  ('Pro',        'pro',        'For growing sales teams with advanced features',         49,   490,  15,   10000,  5000, 5, '{"gmail":true,"calendar":true,"api":true,"webhooks":true}',    1),
  ('Enterprise', 'enterprise', 'Unlimited usage with priority support and custom setup', 199,  1990, 100,  999999, 999999, 99, '{"gmail":true,"calendar":true,"api":true,"webhooks":true,"sso":true,"custom_domain":true}', 2)
ON CONFLICT (slug) DO NOTHING;

-- ─── from api/migrations/015_server_sync_stores.sql ───
-- Sprint 2: Server-side sync for local-first stores
-- Adds tables for smart_views, distribution_lists, and user_preferences

-- Smart views (per-org, synced from viewsStore)
CREATE TABLE IF NOT EXISTS smart_views (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  entity_type   TEXT NOT NULL CHECK (entity_type IN ('contact', 'company', 'deal')),
  name          TEXT NOT NULL,
  name_key      TEXT,
  filters       JSONB NOT NULL DEFAULT '[]',
  sort_field    TEXT,
  sort_direction TEXT CHECK (sort_direction IN ('asc','desc')),
  is_pinned     BOOLEAN NOT NULL DEFAULT FALSE,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS smart_views_org_entity ON smart_views (organization_id, entity_type);

-- Inbox saved views (per-org)
CREATE TABLE IF NOT EXISTS inbox_views (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  query         TEXT NOT NULL DEFAULT '',
  filters       JSONB NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS inbox_views_org ON inbox_views (organization_id);

-- Distribution lists (per-org)
CREATE TABLE IF NOT EXISTS distribution_lists (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id UUID NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  name          TEXT NOT NULL,
  entity_type   TEXT NOT NULL CHECK (entity_type IN ('contact', 'company')),
  member_ids    UUID[] NOT NULL DEFAULT '{}',
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS distribution_lists_org ON distribution_lists (organization_id);

-- User preferences: navigation prefs + onboarding flags (per-user)
CREATE TABLE IF NOT EXISTS user_preferences (
  user_id        UUID PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  navigation     JSONB NOT NULL DEFAULT '{}',
  onboarding     JSONB NOT NULL DEFAULT '{}',
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ─── from api/migrations/016_admin_enhancements.sql ───
-- Sprint 5: Admin panel enhancements
-- Org suspension + impersonation audit log

ALTER TABLE organizations ADD COLUMN IF NOT EXISTS
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended', 'trial'));

CREATE TABLE IF NOT EXISTS impersonation_logs (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  super_admin_id  UUID NOT NULL REFERENCES users(id),
  target_org_id   UUID NOT NULL REFERENCES organizations(id),
  target_user_id  UUID NOT NULL REFERENCES users(id),
  impersonated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  ended_at        TIMESTAMPTZ
);
CREATE INDEX IF NOT EXISTS impersonation_logs_admin ON impersonation_logs (super_admin_id, impersonated_at DESC);
CREATE INDEX IF NOT EXISTS impersonation_logs_org ON impersonation_logs (target_org_id, impersonated_at DESC);

-- ─── from api/migrations/017_bootstrap_super_admin.sql ───
-- One-off bootstrap: promote david@clovrlabs.com to platform super-admin.
-- Recorded in _migrations after first run so it never re-applies.
-- Idempotent by design — the UPDATE is a no-op if the flag is already true,
-- and a no-op if the user does not exist yet (no rows match).

DO $$
DECLARE
  affected INT;
BEGIN
  UPDATE users
     SET is_super_admin = true
   WHERE email = 'david@clovrlabs.com';
  GET DIAGNOSTICS affected = ROW_COUNT;
  RAISE NOTICE '[017] promoted % row(s) to super_admin (target: david@clovrlabs.com)', affected;
END
$$;

-- ─── from api/migrations/018_ai.sql ───
-- ─────────────────────────────────────────────────────────────────────────────
-- 018_ai.sql — AI / agentic assistant
--
-- Three org-scoped tables:
--   ai_conversations  one assistant thread per (org,user)
--   ai_messages       turns within a conversation (user/assistant/tool)
--   ai_usage_log      per-call token accounting for cost/limit visibility
--
-- RLS mirrors migration 002 (ENABLE + org-isolation policy keyed on the
-- app.current_org_id GUC set by set_current_org). The table-owner role bypasses
-- RLS, so app-layer `organization_id = $org` filtering remains the primary
-- enforcement; RLS is defense-in-depth for non-owner roles.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ai_conversations (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id         uuid        REFERENCES users(id) ON DELETE SET NULL,
  title           text        NOT NULL DEFAULT 'New conversation',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_messages (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id uuid        NOT NULL REFERENCES ai_conversations(id) ON DELETE CASCADE,
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  role            text        NOT NULL CHECK (role IN ('user', 'assistant', 'tool', 'system')),
  content         text        NOT NULL DEFAULT '',
  -- Tool calls requested by an assistant turn / executed tool steps, for replay + UI.
  steps           jsonb       NOT NULL DEFAULT '[]',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ai_usage_log (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id         uuid        REFERENCES users(id) ON DELETE SET NULL,
  provider        text        NOT NULL,
  model           text        NOT NULL,
  action          text        NOT NULL,
  input_tokens    integer     NOT NULL DEFAULT 0,
  output_tokens   integer     NOT NULL DEFAULT 0,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ai_conversations_org_user
  ON ai_conversations (organization_id, user_id, updated_at DESC);
CREATE INDEX IF NOT EXISTS idx_ai_messages_conversation
  ON ai_messages (conversation_id, created_at);
CREATE INDEX IF NOT EXISTS idx_ai_usage_org_created
  ON ai_usage_log (organization_id, created_at DESC);

-- ── RLS ──────────────────────────────────────────────────────────────────────
ALTER TABLE ai_conversations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ai_conversations_org ON ai_conversations;
CREATE POLICY rls_ai_conversations_org ON ai_conversations
  USING (organization_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE ai_messages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ai_messages_org ON ai_messages;
CREATE POLICY rls_ai_messages_org ON ai_messages
  USING (organization_id = current_setting('app.current_org_id', true)::uuid);

ALTER TABLE ai_usage_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_ai_usage_log_org ON ai_usage_log;
CREATE POLICY rls_ai_usage_log_org ON ai_usage_log
  USING (organization_id = current_setting('app.current_org_id', true)::uuid);

-- ─── from api/migrations/019_mfa.sql ───
-- ─────────────────────────────────────────────────────────────────────────────
-- 019_mfa.sql — TOTP multi-factor authentication
--
-- mfa_secret_cipher holds the base32 TOTP secret encrypted with AES-256-GCM
-- (services/tokenCipher.ts), so a DB compromise alone does not expose seeds.
-- mfa_enabled is only set true after the user proves possession with a valid
-- code (POST /auth/mfa/enable).
-- ─────────────────────────────────────────────────────────────────────────────
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_enabled boolean NOT NULL DEFAULT false;
ALTER TABLE users ADD COLUMN IF NOT EXISTS mfa_secret_cipher text;

-- ─── from api/migrations/020_security_events.sql ───
-- ─────────────────────────────────────────────────────────────────────────────
-- 020_security_events.sql — tamper-evident security event log (SOC2 CC7 / ISO A.12.4)
--
-- Append-only record of authentication & account-security events. Distinct from
-- audit_log (which is org-scoped business activity): security_events also captures
-- events with no org/actor context (e.g. a failed login for an unknown email),
-- so organization_id and actor_user_id are NULLABLE.
-- ─────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS security_events (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  event_type      text        NOT NULL,
  actor_user_id   uuid        REFERENCES users(id) ON DELETE SET NULL,
  actor_email     text,
  organization_id uuid        REFERENCES organizations(id) ON DELETE SET NULL,
  ip              text,
  user_agent      text,
  detail          text        NOT NULL DEFAULT '',
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_security_events_created ON security_events (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_actor   ON security_events (actor_user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_org     ON security_events (organization_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_security_events_type    ON security_events (event_type, created_at DESC);

-- ─── from api/migrations/021_item_updates.sql ───
-- Monday-style collaboration: threaded "Updates" on CRM items (contacts, companies,
-- deals, leads). Each update can be a reply (parent_id) and can @mention org members.
-- App-layer org scoping is the authoritative control; RLS mirrors the 018_ai pattern
-- as opt-in defense-in-depth (see docs/adr/0001-tenant-isolation-and-rls.md).

CREATE TABLE IF NOT EXISTS item_updates (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  entity_type     text        NOT NULL CHECK (entity_type IN ('contact','company','deal','lead')),
  entity_id       text        NOT NULL,
  parent_id       uuid        REFERENCES item_updates(id) ON DELETE CASCADE,
  author_id       uuid        REFERENCES users(id) ON DELETE SET NULL,
  body            text        NOT NULL,
  mentions        jsonb       NOT NULL DEFAULT '[]',
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  deleted_at      timestamptz
);

CREATE INDEX IF NOT EXISTS idx_item_updates_entity
  ON item_updates (organization_id, entity_type, entity_id, created_at DESC)
  WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_item_updates_parent
  ON item_updates (parent_id) WHERE parent_id IS NOT NULL;

-- ── RLS (opt-in defense-in-depth) ────────────────────────────────────────────
ALTER TABLE item_updates ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_item_updates_org ON item_updates;
CREATE POLICY rls_item_updates_org ON item_updates
  USING (organization_id = current_setting('app.current_org_id', true)::uuid);

-- ─── from api/migrations/022_user_dashboard.sql ───
-- Monday-style composable dashboard: per-user saved widget layout (array of
-- { id, type, title, config }). Stored on the existing user_preferences row.
ALTER TABLE user_preferences ADD COLUMN IF NOT EXISTS dashboard JSONB NOT NULL DEFAULT '{}';

-- ─── from api/migrations/023_lead_form_config.sql ───
-- Web-to-lead form builder: store the form definition (title/fields/success) on the
-- existing lead-capture token, and count submissions. The token (lct_) is the
-- public credential embedded in the form; submissions hit /public/forms/:token.
ALTER TABLE lead_capture_tokens ADD COLUMN IF NOT EXISTS config JSONB NOT NULL DEFAULT '{}';
ALTER TABLE lead_capture_tokens ADD COLUMN IF NOT EXISTS submission_count INTEGER NOT NULL DEFAULT 0;

-- ─── from api/migrations/024_tickets.sql ───
-- Help desk / support tickets (HubSpot Service / Zoho Desk-style). Linked to a
-- contact and/or company, assignable, status + priority. Org-scoped; RLS as opt-in
-- defense-in-depth (app-layer scoping is authoritative — see docs/adr/0001).
CREATE TABLE IF NOT EXISTS tickets (
  id              uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  subject         text        NOT NULL,
  description     text        NOT NULL DEFAULT '',
  status          text        NOT NULL DEFAULT 'open'    CHECK (status IN ('open','pending','resolved','closed')),
  priority        text        NOT NULL DEFAULT 'medium'  CHECK (priority IN ('low','medium','high','urgent')),
  contact_id      uuid        REFERENCES contacts(id)  ON DELETE SET NULL,
  company_id      uuid        REFERENCES companies(id) ON DELETE SET NULL,
  assigned_to     uuid        REFERENCES users(id)     ON DELETE SET NULL,
  created_by      uuid        REFERENCES users(id)     ON DELETE SET NULL,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  resolved_at     timestamptz
);

CREATE INDEX IF NOT EXISTS idx_tickets_org_status ON tickets (organization_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_tickets_org_assignee ON tickets (organization_id, assigned_to);

ALTER TABLE tickets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_tickets_org ON tickets;
CREATE POLICY rls_tickets_org ON tickets
  USING (organization_id = current_setting('app.current_org_id', true)::uuid);

-- ─── from api/migrations/025_booking_pages.sql ───
-- Meeting scheduler / booking links (HubSpot Meetings-style). An owner publishes a
-- booking page with weekly availability; a public visitor books a slot at /book/:token.
-- A booking creates a local calendar_events row + an activity (+ optional lead).
-- (Live Google Calendar push for bookings is a follow-up; availability is computed
-- against existing confirmed bookings for v1.)
CREATE TABLE IF NOT EXISTS booking_pages (
  id                 uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  organization_id    uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  user_id            uuid        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  slug               text        NOT NULL,
  token_hash         text        NOT NULL UNIQUE,
  token_prefix       text        NOT NULL,
  title              text        NOT NULL DEFAULT 'Book a meeting',
  description        text        NOT NULL DEFAULT '',
  duration_minutes   integer     NOT NULL DEFAULT 30,
  timezone           text        NOT NULL DEFAULT 'UTC',
  availability       jsonb       NOT NULL DEFAULT '[]',  -- [{ dow:0-6 (Sun=0), start:'HH:MM', end:'HH:MM' }]
  min_notice_minutes integer     NOT NULL DEFAULT 240,
  max_days_ahead     integer     NOT NULL DEFAULT 60,
  create_lead        boolean     NOT NULL DEFAULT true,
  enabled            boolean     NOT NULL DEFAULT true,
  booking_count      integer     NOT NULL DEFAULT 0,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (organization_id, slug)
);
CREATE INDEX IF NOT EXISTS idx_booking_pages_owner ON booking_pages (user_id, organization_id);
CREATE INDEX IF NOT EXISTS idx_booking_pages_token ON booking_pages (token_hash) WHERE enabled = true;

CREATE TABLE IF NOT EXISTS bookings (
  id                uuid        PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_page_id   uuid        NOT NULL REFERENCES booking_pages(id) ON DELETE CASCADE,
  organization_id   uuid        NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
  start_at          timestamptz NOT NULL,
  end_at            timestamptz NOT NULL,
  invitee_name      text        NOT NULL DEFAULT '',
  invitee_email     text        NOT NULL,
  invitee_notes     text,
  status            text        NOT NULL DEFAULT 'confirmed' CHECK (status IN ('confirmed','cancelled')),
  calendar_event_id uuid        REFERENCES calendar_events(id) ON DELETE SET NULL,
  contact_id        uuid        REFERENCES contacts(id) ON DELETE SET NULL,
  activity_id       uuid        REFERENCES activities(id) ON DELETE SET NULL,
  cancel_token      text        NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_bookings_page_start ON bookings (booking_page_id, start_at);
CREATE INDEX IF NOT EXISTS idx_bookings_org ON bookings (organization_id);
-- Hard guard against double-booking the same slot on a page.
CREATE UNIQUE INDEX IF NOT EXISTS uq_bookings_slot ON bookings (booking_page_id, start_at) WHERE status = 'confirmed';

ALTER TABLE booking_pages ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_booking_pages_org ON booking_pages;
CREATE POLICY rls_booking_pages_org ON booking_pages USING (organization_id = current_setting('app.current_org_id', true)::uuid);
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS rls_bookings_org ON bookings;
CREATE POLICY rls_bookings_org ON bookings USING (organization_id = current_setting('app.current_org_id', true)::uuid);

-- ─── from api/migrations/026_align_deal_terminal_stage_ids.sql ───
-- 026: Align deal terminal stage ids with the app's canonical 'closed_won'/'closed_lost'.
--
-- The frontend (kanban/list/calendar/timeline, dealsStore, deal-health logic),
-- deals.ts status mapping, and analytics.ts all key off 'closed_won'/'closed_lost',
-- but the default pipeline seeded ids 'won'/'lost'. That mismatch meant won/lost
-- deals were never counted, Mark-Won/Lost made cards vanish, and win/loss
-- notifications/automations never fired. pipelines.ts now seeds 'closed_won'/
-- 'closed_lost'; this migration realigns any already-seeded data.

-- Existing deals carrying the old terminal stage ids.
UPDATE deals SET stage = 'closed_won'  WHERE stage = 'won';
UPDATE deals SET stage = 'closed_lost' WHERE stage = 'lost';

-- Existing pipeline stage definitions (jsonb array of {id,name,order,...}).
-- Rebuild each array, rewriting the terminal stage ids while preserving order.
UPDATE pipelines p
SET stages = (
  SELECT jsonb_agg(
    CASE
      WHEN elem->>'id' = 'won'  THEN jsonb_set(elem, '{id}', '"closed_won"')
      WHEN elem->>'id' = 'lost' THEN jsonb_set(elem, '{id}', '"closed_lost"')
      ELSE elem
    END
    ORDER BY ord
  )
  FROM jsonb_array_elements(p.stages) WITH ORDINALITY AS t(elem, ord)
)
WHERE p.stages @> '[{"id":"won"}]' OR p.stages @> '[{"id":"lost"}]';

-- ─── from api/migrations/027_relax_template_category.sql ───
-- 027: Relax the email_templates.category CHECK so UI-created templates persist.
--
-- The template builder offers categories 'intro'/'closing'/'nurture'/'custom',
-- but the original CHECK only allowed 'outreach'/'follow_up'/'proposal'/
-- 'onboarding'/'general', so creating/editing a template from the UI failed the
-- constraint (and the store swallowed the 400, losing the row on reload).
-- Replace the constraint with the union of both sets so legacy rows stay valid
-- and the UI's categories are accepted. (templates.ts zod enum matches this set.)

DO $$
DECLARE c text;
BEGIN
  FOR c IN
    SELECT conname FROM pg_constraint
    WHERE conrelid = 'email_templates'::regclass AND contype = 'c'
  LOOP
    EXECUTE 'ALTER TABLE email_templates DROP CONSTRAINT ' || quote_ident(c);
  END LOOP;
END $$;

ALTER TABLE email_templates
  ADD CONSTRAINT email_templates_category_check
  CHECK (category IN (
    'outreach', 'follow_up', 'proposal', 'onboarding', 'general',
    'intro', 'closing', 'nurture', 'custom'
  ));

-- ─── from api/migrations/028_owner_display_name.sql ───
-- 028: Store record "owner" (assigned_to) as a display-name string, not a user-id FK.
--
-- The entire frontend treats assigned_to as a user's display NAME — the contact
-- and deal owner Selects submit `u.name`, the "my data" filter compares to
-- `currentUser.name`, list search includes the owner name, and detail views render
-- it directly. But contacts/deals/leads.assigned_to were `uuid REFERENCES users(id)`,
-- so creating/editing a record with an owner failed validation (400) and never
-- persisted. leads.assigned_to was already validated as a free string.
--
-- Align the schema with how the app actually uses the column: a text label.
-- (A future "owner-by-id" model would instead change the frontend to submit ids
-- and resolve id->name for display — deliberately not done here to avoid a broad,
-- regression-prone frontend refactor.)

-- Drop the FK constraint backing assigned_to on each table (match by column, so
-- a non-standard constraint name is still handled).
DO $$
DECLARE
  rec record;
BEGIN
  FOR rec IN
    SELECT con.conname, con.conrelid::regclass::text AS tbl
    FROM pg_constraint con
    JOIN pg_attribute att
      ON att.attrelid = con.conrelid AND att.attnum = ANY (con.conkey)
    WHERE con.contype = 'f'
      AND con.conrelid IN ('contacts'::regclass, 'deals'::regclass, 'leads'::regclass)
      AND att.attname = 'assigned_to'
  LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT %I', rec.tbl, rec.conname);
  END LOOP;
END $$;

ALTER TABLE contacts ALTER COLUMN assigned_to TYPE text USING assigned_to::text;
ALTER TABLE deals    ALTER COLUMN assigned_to TYPE text USING assigned_to::text;
ALTER TABLE leads    ALTER COLUMN assigned_to TYPE text USING assigned_to::text;

-- ─── from api/migrations/029_stage_age_and_sequence_sent_at.sql ───
-- 029: support two audit-fix features.
--
-- (B1-24) deals.stage_changed_at — "days in stage" was computed from updated_at,
-- so any unrelated edit reset the counter. Track when the stage last changed.
ALTER TABLE deals ADD COLUMN IF NOT EXISTS stage_changed_at timestamptz NOT NULL DEFAULT now();
-- Seed existing rows from updated_at (closest signal we have) instead of the
-- migration-time default, so current cards don't all reset to "0 days in stage".
UPDATE deals SET stage_changed_at = COALESCE(updated_at, created_at, now());

-- (B1-16) sequence_enrollments.last_sent_at — reply detection keyed off a Gmail
-- last_sent_thread_id that the SMTP send path never wrote, so "stop on contact
-- reply" never fired. Record the time of the last step send so reply detection
-- can match any inbound message from the contact after it (transport-independent).
ALTER TABLE sequence_enrollments ADD COLUMN IF NOT EXISTS last_sent_at timestamptz;

